import React from 'react'
import Head from 'next/head'
import { jsx } from '@emotion/react'

export default function Home() {
  const color = 'white'
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          css={css`
            background-color: hotpink;
            &:hover {
              color: ${color};
            }
          `}
        >
          This has a hotpink background.
        </div>
      </main>

      <footer />
    </div>
  )
}
