import React from 'react'
import Head from 'next/head'
/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'

export default function Home() {
  const color = 'white'
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout></Layout>
      <main>
        <div
          css={css`
            padding: 32px;
            background-color: hotpink;
            font-size: 24px;
            border-radius: 4px;
            &:hover {
              color: ${color};
            }
          `}
        >
          Hover to change color.
        </div>
      </main>

      <footer />
    </div>
  )
}
