import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { jsx, css, Global, ClassNames } from '@emotion/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={{ color: 'hotpink' }}>
          <div
            css={css`
              color: green;
            `}
          />
          <Global
            styles={{
              body: {
                margin: 0,
                padding: 0,
              },
            }}
          />
          <ClassNames>
            {({ css, cx }) => (
              <div
                className={cx(
                  'some-class',
                  css`
                    color: yellow;
                  `
                )}
              />
            )}
          </ClassNames>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
