import React from 'react'
import Head from 'next/head'
/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import { useSelector } from 'react-redux'
import Layout from '../containers/Layout/Layout'
import useLocalStorage from '../Hooks/useLocalStorage'

export default function Home() {
  const [value, setValue] = useLocalStorage('test')
  const auth = useSelector((state) => state.auth)
  console.log(auth)
  setValue('this is a test')
  console.log(value)
  const color = 'white'
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          {auth && auth.logged && <div>welcome</div>}
          {!auth || (!auth.logged && <div>logout</div>)}
          <div
            css={css`
              padding: 32px;
              background-color: hotpink;
              font-size: 24px;
              border-radius: 4px;
              &:hover {
                color: ${color};
              }
            `}
          >
            Hover to change color.
          </div>
        </main>
      </Layout>

      <footer />
    </div>
  )
}
