import React, { useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useDispatch } from 'react-redux'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import FormControl from '../containers/FormControl/FormControl'
import {
  InputEmail,
  InputPassword,
  Button,
  Hyperlink,
  Paragraph,
} from '../components'
import actionTypes from '../config/actionTypes'

export default function Login() {
  const dispatch = useDispatch()
  const [formValue, setFormValue] = useState({})
  const router = useRouter()
  const handleSubmit = (event) => {
    if (event) event.preventDefault()
    dispatch({
      type: actionTypes.LOGIN,
      logged: true,
      email: formValue.email,
    })
    //  console.log('form:', formValue)
    router.push('/')
  }
  const handleOnChange = (name, value) => {
    setFormValue({
      ...formValue,
      [name]: value,
    })
  }
  return (
    <div>
      <Head>
        <title>login page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutAuth>
        <form onSubmit={handleSubmit}>
          <FormControl>
            <InputEmail
              onChange={(value) => handleOnChange('email', value)}
              placeholder="ایمیل"
            />
          </FormControl>
          <FormControl>
            <InputPassword
              onChange={(value) => handleOnChange('password', value)}
              placeholder="کلمه عبور"
            />
          </FormControl>
          <Button type="submit">login</Button>
          <Paragraph align="center">
            <Hyperlink href="/register">ثبت نام کنید</Hyperlink>
          </Paragraph>
        </form>
      </LayoutAuth>

      <footer />
    </div>
  )
}
