import React, { useState } from 'react'
import Head from 'next/head'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import FormControl from '../containers/FormControl/FormControl'
import {
  InputEmail,
  InputPassword,
  InputText,
  Button,
  Hyperlink,
  Paragraph,
} from '../components'

export default function Register() {
  const [formValue, setFormValue] = useState({})
  const handleSubmit = (event) => {
    if (event) event.preventDefault()
    console.log('form:', formValue)
  }
  const handleOnChange = (name, value) => {
    setFormValue({
      ...formValue,
      [name]: value,
    })
  }
  return (
    <div>
      <Head>
        <title>register page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutAuth>
        <form onSubmit={handleSubmit}>
          <FormControl>
            <InputText
              onChange={(value) => handleOnChange('name', value)}
              placeholder="نام"
            />
          </FormControl>
          <FormControl>
            <InputEmail
              onChange={(value) => handleOnChange('email', value)}
              placeholder="ایمیل"
            />
          </FormControl>
          <FormControl>
            <InputPassword
              onChange={(value) => handleOnChange('password', value)}
              placeholder="کلمه عبور"
            />
          </FormControl>
          <Button type="submit" buttonType="secondary">
            register
          </Button>
          <Paragraph align="center">
            <Hyperlink href="/login">وارد شوید</Hyperlink>
          </Paragraph>
        </form>
      </LayoutAuth>

      <footer />
    </div>
  )
}
